services:
  railgun-go:
    image: moeceo/railgun-go:latest
    container_name: railgun-go
    network_mode: bridge
    restart: always
    ports:
      - "8080:8080"
    volumes: 
      - ./database:/app/database
    environment:
      - TZ=Asia/Shanghai